[package]
name = "industrial_evolution"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.11.3", features = [] }
bevy_ecs_tilemap = "0.11.0"
bevy_input_mapper = "0.0.3"
